# -*- coding: utf-8 -*-
"""Lab_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KxgSC01wGq5EvoTl_V9tZuuEHaIm3Y-Q
"""

#Lab-02
#Problem-01
nums=[i for i in range (1,1001) if i%8==0]
print(nums)

#Problem-02
nums=[i for i in range (1,1001) if '6' in str(i)]
print(nums)

#Problem-03
string = "Patience Problems to Drill List Comprehension in your Head"
spaces = [n for n in string if n == ' ']
print(len(spaces))

#Problem-04
string = "Patience Problems to Drill List Comprehension in your Head"
vowel = [n for n in string if n!='a' and n!='A'and n!='e' and n!='E'and n!='i' and n!='I'and n!='o' and n!='O'and n!='u' and n!='U']
print(''.join(vowel))

#Problem-05
string = "Patience Problems to Drill List Comprehension in your Head"
words = string.split(" ")
s = [word for word in words if len(word) < 5]
print(s)

#Problem-06
string = "Patience Problems to Drill List Comprehension in your Head"
s = {word:len(word) for word in words}
print(s)

#Problem-07
nums=[i for i in range (1,1001) if i%8==0]
divisor = [num for num in nums if True in [True for divisor in range(2,10) if num % divisor == 0]]
print(divisor)

#Problem-08
nums=[i for i in range (1,1001)]
divisor = {num:max([divisor for divisor in range(1,10) if num % divisor == 0]) for num in nums}
print(divisor)